/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactsImport } from './routes/contacts'
import { Route as IndexImport } from './routes/index'
import { Route as ContactsIndexImport } from './routes/contacts.index'
import { Route as ContactsCreateImport } from './routes/contacts.create'
import { Route as ContactsContactIdImport } from './routes/contacts.$contactId'
import { Route as ContactsEditContactIdImport } from './routes/contacts.edit.$contactId'

// Create/Update Routes

const ContactsRoute = ContactsImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsIndexRoute = ContactsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactsRoute,
} as any)

const ContactsCreateRoute = ContactsCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ContactsRoute,
} as any)

const ContactsContactIdRoute = ContactsContactIdImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ContactsRoute,
} as any)

const ContactsEditContactIdRoute = ContactsEditContactIdImport.update({
  id: '/edit/$contactId',
  path: '/edit/$contactId',
  getParentRoute: () => ContactsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdImport
      parentRoute: typeof ContactsImport
    }
    '/contacts/create': {
      id: '/contacts/create'
      path: '/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof ContactsCreateImport
      parentRoute: typeof ContactsImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexImport
      parentRoute: typeof ContactsImport
    }
    '/contacts/edit/$contactId': {
      id: '/contacts/edit/$contactId'
      path: '/edit/$contactId'
      fullPath: '/contacts/edit/$contactId'
      preLoaderRoute: typeof ContactsEditContactIdImport
      parentRoute: typeof ContactsImport
    }
  }
}

// Create and export the route tree

interface ContactsRouteChildren {
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsCreateRoute: typeof ContactsCreateRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ContactsEditContactIdRoute: typeof ContactsEditContactIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsCreateRoute: ContactsCreateRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ContactsEditContactIdRoute: ContactsEditContactIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts/': typeof ContactsIndexRoute
  '/contacts/edit/$contactId': typeof ContactsEditContactIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts': typeof ContactsIndexRoute
  '/contacts/edit/$contactId': typeof ContactsEditContactIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/create': typeof ContactsCreateRoute
  '/contacts/': typeof ContactsIndexRoute
  '/contacts/edit/$contactId': typeof ContactsEditContactIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts/'
    | '/contacts/edit/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts'
    | '/contacts/edit/$contactId'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/contacts/$contactId'
    | '/contacts/create'
    | '/contacts/'
    | '/contacts/edit/$contactId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contacts": {
      "filePath": "contacts.tsx",
      "children": [
        "/contacts/$contactId",
        "/contacts/create",
        "/contacts/",
        "/contacts/edit/$contactId"
      ]
    },
    "/contacts/$contactId": {
      "filePath": "contacts.$contactId.tsx",
      "parent": "/contacts"
    },
    "/contacts/create": {
      "filePath": "contacts.create.tsx",
      "parent": "/contacts"
    },
    "/contacts/": {
      "filePath": "contacts.index.tsx",
      "parent": "/contacts"
    },
    "/contacts/edit/$contactId": {
      "filePath": "contacts.edit.$contactId.tsx",
      "parent": "/contacts"
    }
  }
}
ROUTE_MANIFEST_END */
